module.exports = {
  portfolio: [
    { text: '№', align: 'left', class: 'blue lighten-5 text--primary', sortable: true },
    { text: 'Наименование проекта', align: 'left', class: 'blue lighten-5 text--primary', sortable: true, value: 'Name' },
    { text: 'Всего направлено на исполнение', align: 'left', class: 'blue lighten-5 text--primary', sortable: true, value: 'ExecuteTasks' },
    { text: 'Абсолютное значение', align: 'left', class: 'blue lighten-5 text--primary', sortable: true, value: 'ActiveTasksCount' }
  ],
  testData: [
    {
      'Id': '1116',
      'CurrentPlan': '11922',
      'Name': 'Разработка проектной документации для энергоблоков №1, 2 Курской АЭС-2',
      'ExecuteTasks': 578,
      'ActiveTasksCount': 248,
      'DoneTasks': 330,
      'DoneTasksExt': 23,
      'AllOutDatedTasks': 271,
      'Milestone': 1,
      'OutPlanAllOutDatedTasks': 10,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 3,
      'ActiveOutdatedTasks': 248
    },
    {
      'Id': '1415',
      'CurrentPlan': '9495',
      'Name': 'Изготовление и поставка АСУ ТП АЭС Руппур эб. №1, №2',
      'ExecuteTasks': 403,
      'ActiveTasksCount': 118,
      'DoneTasks': 444,
      'DoneTasksExt': 147,
      'AllOutDatedTasks': 247,
      'Milestone': 6,
      'OutPlanAllOutDatedTasks': 66,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 177,
      'ActiveOutdatedTasks': 100
    },
    {
      'Id': '1416',
      'CurrentPlan': '13535',
      'Name': 'Модернизация СКУ энергоблока №1 Калининской АЭС',
      'ExecuteTasks': 690,
      'ActiveTasksCount': 149,
      'DoneTasks': 757,
      'DoneTasksExt': 89,
      'AllOutDatedTasks': 209,
      'Milestone': 6,
      'OutPlanAllOutDatedTasks': 35,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 89,
      'ActiveOutdatedTasks': 120
    },
    {
      'Id': '1516',
      'CurrentPlan': '10708',
      'Name': 'Разработка технического проекта АСУ ТП АЭС АККУЮ',
      'ExecuteTasks': 5,
      'ActiveTasksCount': 5,
      'DoneTasks': 0,
      'DoneTasksExt': 0,
      'AllOutDatedTasks': 5,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 48,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 16,
      'ActiveOutdatedTasks': 5
    },
    {
      'Id': '1617',
      'CurrentPlan': '11112',
      'Name': 'Изготовление и поставка системы АСУТП для э/б №2 ЛЕН АЭС-2',
      'ExecuteTasks': 709,
      'ActiveTasksCount': 126,
      'DoneTasks': 574,
      'DoneTasksExt': 277,
      'AllOutDatedTasks': 392,
      'Milestone': 11,
      'OutPlanAllOutDatedTasks': 114,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 205,
      'ActiveOutdatedTasks': 115
    },
    {
      'Id': '1920',
      'CurrentPlan': '11920',
      'Name': 'АЭС «Куданкулам-3,4»',
      'ExecuteTasks': 623,
      'ActiveTasksCount': 532,
      'DoneTasks': 543,
      'DoneTasksExt': 28,
      'AllOutDatedTasks': 528,
      'Milestone': 15,
      'OutPlanAllOutDatedTasks': 31,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 125,
      'ActiveOutdatedTasks': 500
    },
    {
      'Id': '2021',
      'CurrentPlan': '11214',
      'Name': 'Проектирование АСУ ТП АЭС \'Ханхикиви-1\'',
      'ExecuteTasks': 39,
      'ActiveTasksCount': 14,
      'DoneTasks': 25,
      'DoneTasksExt': 25,
      'AllOutDatedTasks': 36,
      'Milestone': 17,
      'OutPlanAllOutDatedTasks': 7,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 6,
      'ActiveOutdatedTasks': 11
    },
    {
      'Id': '2022',
      'CurrentPlan': '13644',
      'Name': 'АСКУ МФР',
      'ExecuteTasks': 10,
      'ActiveTasksCount': 4,
      'DoneTasks': 6,
      'DoneTasksExt': 4,
      'AllOutDatedTasks': 4,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 10,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 30,
      'ActiveOutdatedTasks': 0
    },
    {
      'Id': '2122',
      'CurrentPlan': '10001',
      'Name': 'АСУ ТП АЭС \'Пакш-2\'',
      'ExecuteTasks': 168,
      'ActiveTasksCount': 51,
      'DoneTasks': 120,
      'DoneTasksExt': 37,
      'AllOutDatedTasks': 88,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 109,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 80,
      'ActiveOutdatedTasks': 51
    },
    {
      'Id': '2123',
      'CurrentPlan': '11924',
      'Name': 'Изготовление, поставка и ввод в действие АСУ ТП энергоблоков №1-4 АЭС \'Эль-Дабаа\'',
      'ExecuteTasks': 218,
      'ActiveTasksCount': 133,
      'DoneTasks': 123,
      'DoneTasksExt': 35,
      'AllOutDatedTasks': 174,
      'Milestone': 3,
      'OutPlanAllOutDatedTasks': 38,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 14,
      'ActiveOutdatedTasks': 139
    },
    {
      'Id': '2223',
      'CurrentPlan': '13031',
      'Name': 'Разработка ПО СВУ и интеграция СВУ с подсистемами АСУ ТП энергоблоков №1,2 Белорусской АЭС',
      'ExecuteTasks': 39,
      'ActiveTasksCount': 14,
      'DoneTasks': 25,
      'DoneTasksExt': 16,
      'AllOutDatedTasks': 23,
      'Milestone': 3,
      'OutPlanAllOutDatedTasks': 6,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 3,
      'ActiveOutdatedTasks': 7
    },
    {
      'Id': '2224',
      'CurrentPlan': '11919',
      'Name': 'НВАЭС2-2',
      'ExecuteTasks': 76,
      'ActiveTasksCount': 19,
      'DoneTasks': 73,
      'DoneTasksExt': 27,
      'AllOutDatedTasks': 41,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 5,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 10,
      'ActiveOutdatedTasks': 14
    },
    {
      'Id': '2325',
      'CurrentPlan': '13738',
      'Name': 'Изготовление и поставка оборудования АСУ ТП для энергоблоков № 1 и № 2 Курской АЭС -2 (поставка)',
      'ExecuteTasks': 108,
      'ActiveTasksCount': 80,
      'DoneTasks': 25,
      'DoneTasksExt': 13,
      'AllOutDatedTasks': 27,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 28,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 45,
      'ActiveOutdatedTasks': 14
    },
    {
      'Id': '2425',
      'CurrentPlan': '10910',
      'Name': 'ИЗГОТОВЛЕНИЕ И ПОСТАВКА КОМПЛЕКСА ОБОРУДОВАНИЯ АВТОМАТИЗИРОВАННОЙ СИСТЕМЫ УПРАВЛЕНИЯ ТЕХНОЛОГИЧЕСКИМ ПРОЦЕССОМ (АСУ ТП) ДЛЯ ЭНЕРГОБЛОКОВ №№ 1, 2, 3, 4 И ОБЩЕСТАНЦИОННЫХ СИСТЕМ АЭС «АККУЮ»',
      'ExecuteTasks': 203,
      'ActiveTasksCount': 45,
      'DoneTasks': 173,
      'DoneTasksExt': 28,
      'AllOutDatedTasks': 73,
      'Milestone': 22,
      'OutPlanAllOutDatedTasks': 1,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 8,
      'ActiveOutdatedTasks': 45
    },
    {
      'Id': '3536',
      'CurrentPlan': '8992',
      'Name': 'АЭС Узбекистан - Стадия PRESALE',
      'ExecuteTasks': 14,
      'ActiveTasksCount': 9,
      'DoneTasks': 5,
      'DoneTasksExt': 3,
      'AllOutDatedTasks': 7,
      'Milestone': 0,
      'OutPlanAllOutDatedTasks': 0,
      'AllOutDatedTasksByGD': 0,
      'AllOutDatedTasksByPZGD': 0,
      'AllContractRequirement': 0,
      'ActiveOutdatedTasks': 4
    }
  ]
}
